### ISSUE TITLE
Crashes with incoming call notification

### ISSUE THREAD

**Issue by mongo56** [edotassi/AmazMod#126]
`E/AndroidRuntime( 1324): FATAL EXCEPTION: main
E/AndroidRuntime( 1324): Process: com.amazmod.service, PID: 1324
E/AndroidRuntime( 1324): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.amazmod.service/com.amazmod.service.ui.NotificationActivity}: java.lang.IllegalArgumentException: width and height must be > 0
E/AndroidRuntime( 1324): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime( 1324): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime( 1324): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime( 1324): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime( 1324): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 1324): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 1324): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 1324): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 1324): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 1324): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 1324): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 1324): Caused by: java.lang.IllegalArgumentException: width and height must be > 0
E/AndroidRuntime( 1324): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
E/AndroidRuntime( 1324): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
E/AndroidRuntime( 1324): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
E/AndroidRuntime( 1324): 	at com.amazmod.service.ui.NotificationActivity.onCreate(NotificationActivity.java:98)
E/AndroidRuntime( 1324): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 1324): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 1324): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/AndroidRuntime( 1324): 	... 10 more
`

**Comment by mongo56** [comment]
Sorry, should have made a search before posting.
