### ISSUE TITLE
NotificationService.mapNotification: java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by edotassi** [edotassi/AmazMod#157]
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.edotassi.amazmod.notification.NotificationService.mapNotification(NotificationService.java:588)
       at com.edotassi.amazmod.notification.NotificationService.onNotificationPosted(NotificationService.java:164)
       at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:317)
       at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:1826)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6696)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
```

**Comment by edotassi** [comment]
closed by 0a168fbe4b6f6e047996b30b0c6d96ea58eddb09
