### ISSUE TITLE
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package 

### ISSUE THREAD

**Issue by edotassi** [edotassi/AmazMod#158]
```
Fatal Exception: android.app.RemoteServiceException: Bad notification posted from package com.edotassi.amazmod: Couldn't inflate contentViewsandroid.widget.RemoteViews$ActionException: java.lang.reflect.InvocationTargetException
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:163)
       at android.app.ActivityThread.main(ActivityThread.java:6238)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

**Comment by lekeCoder** [comment]
How did you solve this issue?
