### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.service.notification.StatusBarNotification.getKey()' on a null object reference

### ISSUE THREAD

**Issue by edotassi** [edotassi/AmazMod#248]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.service.notification.StatusBarNotification.getKey()' on a null object reference
       at com.edotassi.amazmod.notification.NotificationService.onNotificationRemoved(NotificationService.java:183)
       at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:393)
       at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:419)
       at android.service.notification.NotificationListenerService.onNotificationRemoved(NotificationListenerService.java:431)
       at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2108)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6863)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by suhaibabuhamed** [comment]
E/LogKit [E]: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.andreacioccarelli.musicdownloader.data.serializers.DirectLinkResponse.getState()' on a null object reference
