### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.app.Activity.findViewById(int)' on a null object reference

### ISSUE THREAD

**Issue by edotassi** [edotassi/AmazMod#296]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.app.Activity.findViewById(int)' on a null object reference
       at de.mateware.snacky.Snacky$Builder.setActivity(Snacky.java:209)
       at com.edotassi.amazmod.ui.fragment.WatchInfoFragment.updateCheckFailed(WatchInfoFragment.java:245)
       at com.edotassi.amazmod.setup.Setup$1.onFailure(Setup.java:57)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:161)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)
```

**Comment by 0-Whoami** [comment]
> It is caused if you forget to set the view pager object to the page adapter. Something like follows:
> viewPager.setAdapter(introPageAdapter);

Do you mean something like this?

View v = (View)anotherView.findViewById(R.id.id)?

**Comment by Massawe14** [comment]
2022-08-29 17:12:42.281 27180-27180/com.fincare.screenmirroring E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fincare.screenmirroring, PID: 27180
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.app.Activity.findViewById(int)' on a null object reference
        at org.learnprograming.screenmirroring.SecondFragment.onCreateView(SecondFragment.java:31)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:869)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:6733)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:845)
