### ISSUE TITLE
No notification if I enable Custom UI

### ISSUE THREAD

**Issue by fcaronte** [edotassi/AmazMod#69]
As the title, if I active "Enable Custom UI" I stop receive notification on my Amazfit Pace

**Comment by lfom** [comment]
It was disabled when Edo added test notifications using stock library, see #68, should work now (need to build it again after updating sources).

**Comment by lfom** [comment]
@fcaronte watch app is up-to-date too?

**Comment by fcaronte** [comment]
I install the amazfit app from PlayStore and on Pace I've reinstall with last one (swipe to remove work so I think is update) is the original app need special version or PlayStore version is ok?

**Comment by fcaronte** [comment]
@Ifom I try with last 2.5.1 apk version but with same result

**Comment by lfom** [comment]
@fcaronte Amazfit app version doesn't matter, I meant AmazMod on phone and amazmod_service.apk on watch, make sure both AmazMod are up-to-date.

**Comment by fcaronte** [comment]
Delete all folder again and uninstall pace and phone app to retry clean with the same result. The only test I don't try is to remove the old amazmod not supported (because I use daily for the separated notification of WhatsApp) but I understand is not important right?

**Comment by lfom** [comment]
@fcaronte I am not sure if the old AmazMod may interfere or not, but are you sure you have the lasted code in both AmazMod running on phone and watch? It's hard to test with so many versions installed, if the normal notifications work with current up-to-date AmazMod then CustomUI should work too (it does here in my testing setup).

**Comment by fcaronte** [comment]
I see an error in logcat when, with enable custom ui ON,  i receive a notification (i use Facebook messenger for test)
Could you help to understand?
```
 07-13 19:02:43.662 31832-31832/com.edotassi.amazmod W/System.err: java.lang.IllegalArgumentException: class android.content.res.ColorStateList declares multiple JSON fields named mChangingConfigurations
07-13 19:02:43.663 31832-31832/com.edotassi.amazmod W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:167)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
        at com.google.gson.Gson.getAdapter(Gson.java:407)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
        at com.google.gson.Gson.getAdapter(Gson.java:407)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
        at com.google.gson.Gson.getAdapter(Gson.java:407)
07-13 19:02:43.664 31832-31832/com.edotassi.amazmod W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
        at com.google.gson.Gson.getAdapter(Gson.java:407)
        at com.google.gson.internal.bind.ArrayTypeAdapter$1.create(ArrayTypeAdapter.java:48)
        at com.google.gson.Gson.getAdapter(Gson.java:407)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
        at com.google.gson.Gson.getAdapter(Gson.java:407)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
        at com.google.gson.Gson.getAdapter(Gson.java:407)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getFieldAdapter(ReflectiveTypeAdapterFactory.java:136)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.access$100(ReflectiveTypeAdapterFactory.java:49)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.<init>(ReflectiveTypeAdapterFactory.java:106)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:105)
07-13 19:02:43.665 31832-31832/com.edotassi.amazmod W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:161)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:97)
        at com.google.gson.Gson.getAdapter(Gson.java:407)
        at com.google.gson.Gson.toJson(Gson.java:644)
        at com.google.gson.Gson.toJson(Gson.java:631)
        at com.google.gson.Gson.toJson(Gson.java:586)
        at com.google.gson.Gson.toJson(Gson.java:566)
        at xiaofei.library.hermes.util.CodeUtils.encode(CodeUtils.java:39)
        at xiaofei.library.hermes.wrapper.ParameterWrapper.<init>(ParameterWrapper.java:70)
        at xiaofei.library.hermes.sender.Sender.getParameterWrappers(Sender.java:136)
        at xiaofei.library.hermes.sender.Sender.send(Sender.java:153)
        at xiaofei.library.hermes.internal.HermesInvocationHandler.invoke(HermesInvocationHandler.java:48)
07-13 19:02:43.668 31832-31832/com.edotassi.amazmod W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy5.post(Unknown Source)
        at xiaofei.library.hermeseventbus.HermesEventBus$3.call(HermesEventBus.java:198)
        at xiaofei.library.hermeseventbus.HermesEventBus$3.call(HermesEventBus.java:195)
        at xiaofei.library.hermeseventbus.HermesEventBus$1.call(HermesEventBus.java:169)
        at xiaofei.library.hermeseventbus.HermesEventBus$1.call(HermesEventBus.java:166)
        at xiaofei.library.concurrentutils.ObjectCanary2.action(ObjectCanary2.java:85)
        at xiaofei.library.hermeseventbus.HermesEventBus.actionInternal(HermesEventBus.java:166)
        at xiaofei.library.hermeseventbus.HermesEventBus.post(HermesEventBus.java:195)
07-13 19:02:43.669 31832-31832/com.edotassi.amazmod W/System.err:     at com.edotassi.amazmod.notification.NotificationService.onNotificationPosted(NotificationService.java:96)
        at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:317)
        at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:1909)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
    xiaofei.library.hermes.util.HermesException
07-13 19:02:43.670 31832-31832/com.edotassi.amazmod W/System.err:     at xiaofei.library.hermes.util.CodeUtils.encode(CodeUtils.java:45)
        at xiaofei.library.hermes.wrapper.ParameterWrapper.<init>(ParameterWrapper.java:70)
        at xiaofei.library.hermes.sender.Sender.getParameterWrappers(Sender.java:136)
        at xiaofei.library.hermes.sender.Sender.send(Sender.java:153)
        at xiaofei.library.hermes.internal.HermesInvocationHandler.invoke(HermesInvocationHandler.java:48)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy5.post(Unknown Source)
        at xiaofei.library.hermeseventbus.HermesEventBus$3.call(HermesEventBus.java:198)
        at xiaofei.library.hermeseventbus.HermesEventBus$3.call(HermesEventBus.java:195)
        at xiaofei.library.hermeseventbus.HermesEventBus$1.call(HermesEventBus.java:169)
        at xiaofei.library.hermeseventbus.HermesEventBus$1.call(HermesEventBus.java:166)
        at xiaofei.library.concurrentutils.ObjectCanary2.action(ObjectCanary2.java:85)
        at xiaofei.library.hermeseventbus.HermesEventBus.actionInternal(HermesEventBus.java:166)
        at xiaofei.library.hermeseventbus.HermesEventBus.post(HermesEventBus.java:195)
07-13 19:02:43.671 31832-31832/com.edotassi.amazmod W/System.err:     at com.edotassi.amazmod.notification.NotificationService.onNotificationPosted(NotificationService.java:96)
        at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java:317)
        at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:1909)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
07-13 19:02:43.672 31832-31832/com.edotassi.amazmod E/HERMES_INVOCATION: Error occurs. Error 6: Error occurs when Gson encodes Object com.edotassi.amazmod.event.OutcomingNotification@4a0c70c to Json.
07-13 19:03:00.299 31832-31832/com.edotassi.amazmod D/AmazMod:
```

**Comment by fcaronte** [comment]
this is the logcat when enable the "Custom UI" option
```
07-13 19:08:30.794 31832-31832/com.edotassi.amazmod D/AccessibilityManager: accessibility service is not enabled
07-13 19:08:31.891 31832-4306/com.edotassi.amazmod V/FA: Inactivity, disconnecting from the service
07-13 19:08:36.291 31832-31832/com.edotassi.amazmod D/ViewRootImpl@cec73e[SettingsActivity]: ViewPostIme pointer 0
07-13 19:08:36.381 31832-31832/com.edotassi.amazmod D/ViewRootImpl@cec73e[SettingsActivity]: ViewPostIme pointer 1
07-13 19:08:36.382 31832-31832/com.edotassi.amazmod D/AbsListView: onTouchUp() mTouchMode : 0
07-13 19:08:36.464 31832-31832/com.edotassi.amazmod D/AccessibilityManager: accessibility service is not enabled
07-13 19:08:36.488 31832-31832/com.edotassi.amazmod I/chatty: uid=10729(u0_a729) com.edotassi.amazmod identical 10 lines
07-13 19:08:36.488 31832-31832/com.edotassi.amazmod D/AccessibilityManager: accessibility service is not enabled
07-13 19:08:42.396 31832-31832/com.edotassi.amazmod D/AmazMod: ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
07-13 19:08:42.397 31832-31832/com.edotassi.amazmod D/AmazMod: │ Thread: main
```

**Comment by fcaronte** [comment]
PS i try to install official app and give same error

**Comment by lfom** [comment]
You still didn't say if the AmazMod apps you are using have the latest code... Do they?

I don't see you in the beta test group, so unless you have updated the code and built it from sources, it won't work.

**Comment by fcaronte** [comment]
no, I'm not in the beta group but I clone this git myself and for me is update at 11/07 whit merge #68 and if I go to see the file you push to merge, they are update and so for me is last update, I don't know if I need some other step but if I disable custom ui the new feature to remove the notification on the smartphone with a swipe on smartwatch is working well so I think is the right version

**Comment by daenny** [comment]
same here, I have build AmazMod and AmazModService from the latest master of this repo and no notifications are coming through when enabling "CustomUI" option. 
On the watch the service is shown as version: 0.0.1_(788) and the app shows in the changelog the v1.0.8-ALPHA
I am using AndroidExtended 8.1 on a zuk z2pro. 
I have build both (app and service) as release version (i.e. using export signed apk), not debug not sure if that might be the issue. I installed via adb on the watch and directly on the phone.

**Comment by fcaronte** [comment]
thanks, so I'm not the only one with this problem

**Comment by lfom** [comment]
I don't know how you are building them as there is a private file that is needed for crash analytics, I think... I have attached my latest build, you can try if you want (uninstall previous versions first, watch must be restarted for it to work after installation), everything is working fine here.

[AmazMod_alpha.zip](https://github.com/edotassi/AmazMod/files/2216491/AmazMod_alpha.zip)

**Comment by daenny** [comment]
just tested your version @lfom , and I get the same behaviour: notifications work for when not using Custom UI, after enabling custom UI nothing is shown on the watch. 

I am running https://forum.xda-developers.com/smartwatch/amazfit/paceficator-project-wos-2-6-0-12-rom-v0-t3794922 this ROM.

**Comment by fcaronte** [comment]
same result for me :(

Il giorno sab 21 lug 2018 alle ore 23:52 Daniel Claes <
notifications@github.com> ha scritto:

**Comment by lfom** [comment]
@fcaronte @daenny 
Did you uninstall older versions? What is the AmazMod Service version that shows in AmazMod on phone? Can you hide/show the battery chart?

**Comment by fcaronte** [comment]
Yes all clean because in this day I wipe smartphone and smartwatch and so was the first installs of your apk. For the version show 5xx (not remember correctly) but not try the battery disable. In my previous logcan you can see anything strange?


Inviato da smartphone Samsung Galaxy.
-------- Messaggio originale --------Da: lfom <notifications@github.com> Data: 22/07/18  01:49  (GMT+01:00) A: edotassi/AmazMod <AmazMod@noreply.github.com> Cc: fcaronte <fra.caronte@gmail.com>, Mention <mention@noreply.github.com> Oggetto: Re: [edotassi/AmazMod] No notification if I enable Custom UI (#69) 
@fcaronte @daenny

Did you uninstall older versions? What is the AmazMod Service version that shows in AmazMod on phone? Can you hide/show the battery chart?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/edotassi/AmazMod","title":"edotassi/AmazMod","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/edotassi/AmazMod"}},"updates":{"snippets":[{"icon":"PERSON","message":"@lfom in #69: @fcaronte @daenny \r\nDid you uninstall older versions? What is the AmazMod Service version that shows in AmazMod on phone? Can you hide/show the battery chart? "}],"action":{"name":"View Issue","url":"https://github.com/edotassi/AmazMod/issues/69#issuecomment-406830539"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/edotassi/AmazMod/issues/69#issuecomment-406830539",
"url": "https://github.com/edotassi/AmazMod/issues/69#issuecomment-406830539",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [edotassi/AmazMod] No notification if I enable Custom UI (#69)",
"sections": [
{
"text": "",
"activityTitle": "**lfom**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@lfom",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"edotassi/AmazMod\",\n\"issueId\": 69,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"edotassi/AmazMod\",\n\"issueId\": 69\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/edotassi/AmazMod/issues/69#issuecomment-406830539"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 355410768\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by daenny** [comment]
Yes I have cleaned everything (actually even a factory reset). Watch version shows 802 and I can hide battery graph on the phone...

**Comment by lfom** [comment]
@daenny Using "Force English" gives the same result? What Android version on phone? Do you know how to get a logcat, filtering "amazmod" in the results?

**Comment by lfom** [comment]
@fcaronte Thanks, it seems to be an error when running on Oreo only, and it's related to gson files. I don't know how to fix it and I don't have anything to test the app running Oreo right now, so probably we need to wait for Edo, maybe he can find out what's going on...

**Comment by fcaronte** [comment]
Ok thanks, wait for it 🤞

**Comment by lfom** [comment]
Well, I had some time today and installed Oreo emulator and I could reproduce the error, it's related to HermesEventBus. I did a small change in the code and to my surprise I didn't get any more crashes in emulator, what it doesn't mean that if fixed the problem (I cannot test data transfer with emulator). So, it's the newest build, no errors on Oreo emulator:

[AmazMod_1.0.10_ALPHA.zip](https://github.com/edotassi/AmazMod/files/2234200/AmazMod_1.0.10_ALPHA.zip)

As always, completely uninstall old versions before installing this one, as there are many changes in preferences, etc.

**Comment by fcaronte** [comment]
The zip contain only server, the phone app it's the same version or need the new APK too?

**Comment by lfom** [comment]
@fcaronte Sorry, please download again (now it has both).

**Comment by fcaronte** [comment]
No, no notifications when enable custom UI, now need to go work but when return home I will try to see the logcat

**Comment by fcaronte** [comment]
@lfom Today I update again the last change o battery ecc and try again and I make a discovery :) so, i found that if i do this step I have 1 time notification working.
1 put "adb reboot" on termial to restart my phone
2 try notification and working :)
3 try again and not work anymore :(
I add the working logcat and screen of Pace notification (on facebook messenger i don't see the reply button is normal?)
[ha funzionato.txt](https://github.com/edotassi/AmazMod/files/2241978/ha.funzionato.txt)
![30-07-2018-18-08-01](https://user-images.githubusercontent.com/26366403/43409437-371c2fee-9424-11e8-8fe3-c3446c654bfd.png)

**Comment by fcaronte** [comment]
after boot for few time often is work but then stop working

could this error can help?
see logcat
[logcat.txt](https://github.com/edotassi/AmazMod/files/2242163/logcat.txt)

**Comment by fcaronte** [comment]
Sorry, I put last complete Logcat.
Is start from clear boot phone, receive notification (working), open app and send notification (working) close app and phone stanby, receive notification (working) pass some time send notification (NOT working) in this logcat hope to can find the problem
[logcat from Boot work to NOT work.txt](https://github.com/edotassi/AmazMod/files/2242233/logcat.from.Boot.work.to.NOT.work.txt)

**Comment by lfom** [comment]
No errors anymore on Oreo using emulator, so hopefully this can be closed soon. ;)

[AmazMod_1.0.14_ALPHA.zip](https://github.com/edotassi/AmazMod/files/2245106/AmazMod_1.0.14_ALPHA.zip)

**Comment by Matt-LaFayette** [comment]
Working for me!! Hope fcaronte has the same success!

**Comment by fcaronte** [comment]
Can confirm BUG IS FIXED 👍  good job. 🥇 
A curiosity, is my last logcat help you to fix?
For me we can close 👍

**Comment by lfom** [comment]
@fcaronte actually all logcats showed the same cryptic error, what really helped was that you insisted in the bug while I didn't see any. I didn't understand the whole transport algorithm then, when I tried to figure it out and found another bug, this helped me to find out what was going on. ;)
